# Generated by Django 6.0.8 on 2026-08-05 12:36

import django.db.models.deletion
import ventas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('calibre_acero', models.IntegerField()),
                ('precio_base_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('LAMINA', 'Lamina a la medida'), ('MESON', 'Meson'), ('CAMPANA', 'Campana extractora'), ('FREIDORA', 'Freidora (estandar)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('nit_o_cedula', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('HOTEL', 'Hotel'), ('PERSONA', 'Persona natural')], default='PERSONA', max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventas.producto')),
            ],
            bases=(ventas.models.ProductoAMedida, 'ventas.producto'),
        ),
        migrations.CreateModel(
            name='Freidora',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventas.producto')),
            ],
            bases=('ventas.producto',),
        ),
        migrations.CreateModel(
            name='Lamina',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventas.producto')),
            ],
            bases=(ventas.models.ProductoAMedida, 'ventas.producto'),
        ),
        migrations.CreateModel(
            name='Meson',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ventas.producto')),
            ],
            bases=(ventas.models.ProductoAMedida, 'ventas.producto'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al cliente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], default='BORRADOR', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('largo_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_COLA', 'En cola'), ('CORTE', 'Corte'), ('SOLDADURA', 'Soldadura'), ('PULIDO', 'Pulido'), ('TERMINADA', 'Terminada'), ('ENTREGADA', 'Entregada')], default='EN_COLA', max_length=10)),
                ('fecha_estimada_entrega', models.DateField()),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden', to='ventas.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ANTICIPO', 'Anticipo (50%)'), ('SALDO', 'Saldo final')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('aprobado', models.BooleanField(default=False)),
                ('referencia', models.CharField(blank=True, max_length=64)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.ordenfabricacion')),
            ],
        ),
    ]
